baseURL = 'https://fabio-lab001.github.io/'
languageCode = 'en-us'
title = '[FABIO-LAB]'
author = "genesissmooth1"
description = "Computer Science & Tech Enthusiast"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "identity"
    name = "Identity"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 3
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 4
    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
